<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-22 17:07

from django.db import migrations
=======
# Generated by Django 5.2.8 on 2025-11-22 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
>>>>>>> 53a8404ef9bfe451dbb0d667faf5fbc46ccafefa


class Migration(migrations.Migration):

<<<<<<< HEAD
    dependencies = [
    ]

    operations = [
=======
    initial = True

    dependencies = [
        ('halltickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('result_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='halltickets.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'exam')},
            },
        ),
>>>>>>> 53a8404ef9bfe451dbb0d667faf5fbc46ccafefa
    ]
