# Generated by Django 5.2.7 on 2025-11-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halltickets', '0001_initial'),
        ('marksheets', '0001_initial'),
        ('students', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Exam', max_length=255)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(default='F', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halltickets.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
