# Generated by Django 5.2.8 on 2025-12-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marksheets', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
